name: "Publish to Docker Hub"

run-name: "Publishing ${{ github.event.release.tag_name }} to Docker Hub"

on:
  release:
    types: [ "published" ]

permissions:
  { }

jobs:
  publish-to-docker-hub:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"
        with:
          platforms: "linux/amd64,linux/arm64"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Extract metadata"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: "mrjackyliang/pfsense-actions"

      - name: "Login"
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build and push"
        uses: "docker/build-push-action@v6"
        with:
          platforms: "linux/amd64,linux/arm64"
          push: "true"
          tags: |
            "mrjackyliang/pfsense-actions:latest"
            "mrjackyliang/pfsense-actions:${{ github.event.release.tag_name }}"
